#!/usr/bin/env php
<?php

/**
 * 便捷读取proto内容，不需要实现复杂proto-gen插件
 */
$input     = new Input($argv);
$protoPath = realpath($input->get('proto_path'));

foreach (DirsHelp::getDirs($protoPath, '.proto') as $file) {
    $parser    = new ProtoParser($file);
    $goPackage = $parser->geOptions('go_package');

    foreach ($parser->getServices() as $server) {
        print_r($server);
    }
}

// ------------------------------
// ---------- 以下只封装 ----------
// ---------- 不需要修改 ----------
// ------------------------------

// 解析proto到php可识别结构
class ProtoParser
{
    private $file;
    private $syntax;
    private $services = [];
    private $option = [];
    private $import = [];
    private $package;

    public function __construct(string $file)
    {
        $this->file = $file;

        $this->parser();
    }

    public function getFile(): string
    {
        return $this->file;
    }

    private function parser()
    {
        $fileContextArr = file($this->file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

        for ($i = 0; $i < count($fileContextArr);) {
            $str     = $fileContextArr[$i];
            $strArr  = explode(' ', $str);
            $trimStr = trim($str);

            // 处理完后，返回下个结构的开始点
            switch ($strArr[0]) {
                case 'syntax':
                    $i++;
                    $this->syntax = strCut('"', '";', explode('=', $trimStr)[1]);
                    break;
                case 'package':
                    $i++;
                    $this->package = strCut(' ', ';', $trimStr);
                    break;
                case 'import':
                    $i++;
                    $this->import[] = strCut('"', '";', $trimStr);
                    break;
                case 'option':
                    $i++;
                    $this->option[trim(strCut(' ', ' =', $trimStr))] = strCut('"', '";', explode('=', $trimStr)[1]);
                    break;
                case 'service':
                    $i = $this->loadServices($i, $fileContextArr);
                    break;
                case 'message':// TODO message
                    $i++;
                    break;
                default:
                    $i++;
                    break;
            }
        }
    }

    private function loadServices(int $j, array $fileContextArr): int
    {
        $need = [];
        for ($i = $j; $i <= count($fileContextArr); $i++) {
            $str    = $fileContextArr[$i];
            $need[] = $str;

            if ($str === '}') {
                $i++;
                break;
            }
        }
        $services   = new ProtoService();
        $serviceRpc = new ProtoServiceRpc();
        $docTemp    = '';
        $_count     = 0;
        $_onRpc     = false;
        foreach ($need as $str) {
            $trimStr = trim($str);
            $strArr  = explode(' ', $trimStr);

            switch ($strArr[0]) {
                case '': // 空格 = 重置
                    $docTemp = '';
                    break;
                case '//': // 注视
                    $docTemp = $trimStr;
                    break;
                case 'rpc':
                    $_onRpc = true;
                    if ($docTemp) {
                        $serviceRpc->doc = $docTemp;
                        $docTemp         = '';
                    }
                    $serviceRpc->name   = strCut('rpc', '(', $trimStr);
                    $serviceRpc->params = [
                        'request'  => strCut('(', ')', $trimStr),
                        'response' => strCut('(', ')', explode('returns', $trimStr)[1]),
                    ];
                    break;
                case 'option':
                    $optType  = strCut('(', ')', $trimStr);
                    $optValue = strCut('"', '";', $trimStr);

                    if ($_onRpc) {
                        $serviceRpc->option[$optType] = $optValue;
                    } else {
                        $services->option[$optType] = $optValue;
                    }
                    break;
                case '{':
                    $_count++;
                    break;
                case '}':
                    $_count--;
                    if ($_count <= 0) {
                        if ($serviceRpc->name) {
                            $services->rpc[] = $serviceRpc;
                        }

                        $serviceRpc = new ProtoServiceRpc();
                        $docTemp    = '';
                        $_count     = 0;
                        $_onRpc     = false;
                    }

                    break;
                default:
                    if (strlen($trimStr) >= 1) {
                        $last = strlen($trimStr);

                        if ($trimStr[$last - 1] == '{') {
                            $_count++;
                        }
                    }

                    break;
            }
        }

        $this->services[] = $services;

        return $i;
    }

    /**
     * @return ProtoService[]
     */
    public function getServices(): array
    {
        return $this->services;
    }

    public function geOptions($key = null)
    {
        if ($key) {
            return $this->option[$key] ?? '';
        }
        return $this->option;
    }
}

class ProtoService
{
    public $rpc = [];
    public $option = [];

    public function getRpcList(): array
    {
        return $this->rpc;
    }
}

class ProtoServiceRpc
{
    public $doc = '';
    public $name;
    public $option = [];
    public $params = [];
}

class Input
{
    /**
     * @var array
     */
    private $argv = [];

    public function __construct(array $argv)
    {
        foreach ($argv as $item) {
            if (strpos($item, '--') === 0) {
                $arr = explode('=', explode('--', $item)[1]);

                $this->argv[$arr[0]] = $arr[1];
            }
        }
    }

    public function get(string $key): string
    {
        return $this->argv[$key] ?? '';
    }
}

class DirsHelp
{
    public static function getDirs(string $path, string $ext = null): array
    {
        $arr = [];
        if (is_dir($path)) {
            $dir = scandir($path);
            foreach ($dir as $value) {
                $sub_path = $path.'/'.$value;
                if ($value == '.' || $value == '..') {
                    continue;
                } else {
                    if (is_dir($sub_path)) {
                        $arr = array_merge($arr, self::getDirs($sub_path));
                    } else {
                        //.$path 可以省略，直接输出文件名
                        if ($ext === null || strpos($value, $ext) != false) {
                            $arr[] = $path.'/'.$value;
                        }
                    }
                }
            }
        }
        return $arr;
    }
}

function strCut($begin, $end, $str): string
{
    $b = mb_strpos($str, $begin) + mb_strlen($begin);
    $e = mb_strpos($str, $end) - $b;
    return mb_substr($str, $b, $e);
}